In [ ]:
Numpy array has less memory consumption then python list

In [2]:
import sys
import numpy as np

#List --->
l = range(1000)
print(sys.getsizeof(5) * len(l))

#numpy array --->
array = np.arange(1000)
print(array.size*array.itemsize)

28000
4000


In [4]:
# 1-D Array --->
a=np.array([1,2,3])
print(a)
print(a[0])
print(a.ndim)

[1 2 3]
1
1


In [14]:
# 2-D Array --->
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b[0][0])
print(b.ndim)

[[1 2 3]
 [4 5 6]]
1
2


In [6]:
#bit size --->
print(a.itemsize)

4


In [8]:
#datatype ---->
print(a.dtype)

int32


In [22]:
b=np.array([[1,2,3],[4,5,6]], dtype=np.float64)
print(b.itemsize)
print(b.dtype)
print(b)

c=np.array([[1,2,3],[4,5,6]], dtype=complex)
print(c.itemsize)
print(c.dtype)
print(c)

8
float64
[[1. 2. 3.]
 [4. 5. 6.]]
16
complex128
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [19]:
#total no. of elements ---->
a=np.array([1,2,3])
print(a.size)
b=np.array([[1,2,3],[4,5,6]])
print(b.size)

3
6


In [20]:
#shape ---->
a=np.array([1,2,3])
print(a.shape)
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)

(3,)
(2, 3)


In [23]:
#zeros ---->
a=np.zeros(5)
print(a)
a=np.zeros((3,2))
print(a)

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [24]:
#ones ---->
a=np.ones(5)
print(a)
a=np.ones((3,2))
print(a)

[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [25]:
#range ---->
l=range(5)
print(l)

range(0, 5)


In [30]:
#arange ---->
l=np.arange(1,5)
print(l)
l=np.arange(1,8,2)
print(l)

[1 2 3 4]
[1 3 5 7]


In [32]:
#linespace ---->
l=np.linspace(1,5,10)
print(l)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
