NumPy

In [ ]:
# Numpy is the fundamental package for scientific computing in python
#It is a Python library that provides a multidimensional array object, various dervied ojects

In [ ]:
# Numpy Array is a grid of values and it cintains information about the raw data, how to locate  an element, and how to interpret an element

In [20]:
'''
Numpy Vs Python list ---->
Advantages--->
- Consume less memory
- fast as compared to Python list
- convenient to use
'''

'\nNumpy Vs Python list ---->\nAdvantages--->\n- Consume less memory\n- fast as compared to Python list\n- convenient to use\n'

In [ ]:
# Installation: pip install numpy
# import NumPy: import numpy as np

In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [14]:
import numpy as np
#array
x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
#List
y=[1,2,3,4,5]
print(y)
print(type(y))

[1, 2, 3, 4, 5]
<class 'list'>


In [18]:
#processing time--->
%timeit [j**4 for j in range(1,9)]
%timeit np.arange(1,9)**4

812 ns ± 9.17 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
2.69 μs ± 95.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [22]:
l=[]
for i in range(1,5):
    int_l=int(input("Enter Number: "))
    l.append(int_l)
print(np.array(l))

Enter Number:  9
Enter Number:  8
Enter Number:  7
Enter Number:  6


[9 8 7 6]


In [ ]:
'''
Dimensions in Array---->
- 1D Array
- 2D Array
- 3D Array
- Higher Dimension Array
'''

In [28]:
ar1=np.array([1,2,3,4,5])
print(ar1)
print(ar1.ndim)

ar2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ar2)
print(ar2.ndim)

ar3=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(ar3)
print(ar3.ndim)

[1 2 3 4 5]
1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
3


In [32]:
ar1=np.array([1,2,3,4,5], ndmin=10)
print(ar1)
print(ar1.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


In [34]:
#Array filled with 0's

import numpy as np
ar_zeros=np.zeros(10)
print(ar_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [38]:
import numpy as np
ar_zeros=np.zeros((3,4))
print(ar_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [44]:
#Array filled with 1's
import numpy as np
ones=np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [46]:
import numpy as np
ones=np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [48]:
#Empty
ar_em=np.empty(4)
print(ar_em)

[3.39519327e-313 5.43230923e-312 2.75010655e-311 8.69169476e-311]


In [50]:
#Range
ar_rn=np.arange(4)
print(ar_rn)

[0 1 2 3]


In [54]:
#Range
ar_rn=np.arange(100,200,5)
print(ar_rn)

[100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]


In [64]:
#Diagonal element filled with 1's
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [58]:
#Diagonal
ar_dia=np.eye(2)
print(ar_dia)

[[1. 0.]
 [0. 1.]]


In [60]:
#Diagonal
ar_dia=np.eye(9)
print(ar_dia)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [62]:
#Diagonal
ar_dia=np.eye(4,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [76]:
#linspace- we get a continuous number
ar_lin=np.linspace(1,10,num=5) #number between 1 to 10
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [72]:
#linspace
ar_lin=np.linspace(1,5,num=5)
print(ar_lin)

[1. 2. 3. 4. 5.]


In [74]:
#linspace
ar_lin=np.linspace(1,10,num=2)
print(ar_lin)

[ 1. 10.]


In [ ]:
''' 
Create Numpy array with 
rand(): The function is used to generate a random value between 0 to 1.
randn(): the function is used to generate a random value close to zero. This may return positive or negative numbers as well.
ranf(): the function for doing random sampling in numpy. it returns an array of specified shape and fills it with random float in the half-open interval [0.0,1.0], excluding 1
randint(): The function is used to generate a random number between a given range
'''

In [78]:
#rand()
import numpy as np
var=np.random.rand(10)
print(var)

[0.90866863 0.17435913 0.12044839 0.91771745 0.37476687 0.44451416
 0.03977144 0.75192096 0.50041564 0.50373934]


In [80]:
var1=np.random.rand(2,5)
print(var1)

[[0.90420683 0.64347115 0.36241122 0.0647352  0.44806449]
 [0.74106789 0.34855368 0.31580604 0.0447355  0.59991799]]


In [84]:
#randn()
import numpy as np
var=np.random.randn(10)
print(var)

[-0.41961974  1.34180283  0.34611137 -0.15948905  0.8095683  -0.07961222
  1.12785121 -0.13608666  1.11509236 -0.47418062]


In [86]:
#ranf()
var=np.random.ranf(10)
print(var)

[0.22491639 0.2463363  0.05682295 0.56508565 0.74704766 0.58923732
 0.42947275 0.43973058 0.07777312 0.50384515]


In [94]:
#randint()
var=np.random.randint(5,10,5)
print(var)

[5 9 6 5 9]


In [ ]:
#Datatype in Numpy
- bool_
- int_
- intc
- intp
- int8
- int16
- int32
- int64
- uint8
- uint16
- uint32
- uint64
- float_
- float32
- float64
- complex_
- complex64
- complex128  

In [96]:
import numpy as np
var = np.array([1,2,3,4])
print("Data Type: ", var.dtype)

Data Type:  int32


In [98]:
import numpy as np
var = np.array([1.2,2,3,4])
print("Data Type: ", var.dtype)

Data Type:  float64


In [100]:
import numpy as np
var = np.array(["S","A","H","I","L"])
print("Data Type: ", var.dtype)

Data Type:  <U1


In [102]:
import numpy as np
var = np.array(["S","A","H","I",1,58])
print("Data Type: ", var.dtype)

Data Type:  <U11


In [ ]:
#list of character that are used to represent dtype in Numpy:
i - integer
b - boolean
u - unsigned interger
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - the fixed chunk of memory for other types (void)

In [108]:
x= np.array([1,2,3,4], dtype=np.int8)
print("DataType:", x.dtype)

DataType: int8


In [110]:
x= np.array([1,2,3,4], dtype="f")
print("DataType:", x.dtype)

DataType: float32


In [ ]:
#Arithmetic Operations---->
np.add(a,b) OR a+b
np.subtract(a,b) OR a-b
np.multiply(a,b) OR a*b
np.divide(a,b) OR a/b
np.mod(a,b) OR a%b
np.power(a,b) OR a**b
np.reciprocal(a) OR 1*a

In [112]:
import numpy as np
var=np.array([1,2,3,4,5,6])
varadd=var+3
print(varadd)

[4 5 6 7 8 9]


In [114]:
import numpy as np
var=np.array([1,2,3,4,5,6])
varr=np.array([1,2,3,4,5,6])
varadd=var+varr
print(varadd)

[ 2  4  6  8 10 12]


In [116]:
import numpy as np
var=np.array([1,2,3,4,5,6])
varadd=var-3
print(varadd)

[-2 -1  0  1  2  3]


In [120]:
import numpy as np
var=np.array([1,2,3,4,5,6])
varr=np.array([1,2,3,4,5,1])
varadd=var-varr
print(varadd)

[0 0 0 0 0 5]


In [122]:
import numpy as np
var=np.array([1,2,3,4,5,6])
varadd=var/3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333 1.66666667 2.        ]


In [124]:
import numpy as np
var=np.array([1,2,3,4,5,6])
varadd=var%3
print(varadd)

[1 2 0 1 2 0]


In [128]:
import numpy as np
var=np.array([[1,2,3,4],[1,2,3,4]])
varr=np.array([[1,2,3,4],[1,2,3,4]])
varadd=var+varr
print(varadd)

[[2 4 6 8]
 [2 4 6 8]]


In [130]:
# Arithmetic Functions ---->
np.min(x)
np.max(x) 
np.argmin(x) #return index
np.argmax(x)
np.sqrt(x)
np.sin(x)
np.cos(x)
np.cumsum(x)

SyntaxError: invalid syntax (1613942812.py, line 2)

In [140]:
import numpy as np
var=np.array([1,2,3,4,5,6])
print(np.min(var))
print(np.max(var))
print(np.min(var), np.argmin(var))
print(np.max(var), np.argmax(var))
print(np.sqrt(var))

1
6
1 0
6 5
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [138]:
import numpy as np
var=np.array([[2,1,3],[9,5,6]])
print(np.min(var), np.argmin(var))
print(np.max(var), np.argmax(var))

1 1
9 3


In [144]:
import numpy as np
var=np.array([1,2,3,4,5,6])
print(np.sin(var))
print(np.cos(var))
print(np.cumsum(var))


[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
[ 1  3  6 10 15 21]


In [7]:
#Shape ---->
import numpy as np
var=np.array([[1,2],[2,3]])
print(var)
print("Shape: ", var.shape)

[[1 2]
 [2 3]]
Shape:  (2, 2)


In [11]:
#Reshape---->
import numpy as np
var=np.array([1,2,3,4,5,6])
x=var.reshape(3,2) #(row,coln)
print(x)
print(x.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [17]:
#broadcasting--->
?????

Object `???` not found.


In [25]:
#indexing-->
import numpy as np
var=np.array([9,5,8,7])
print(var[0])
print(var[1])
print(var[2])
print(var[3])
print(var[-1])
print(var[-2])
print(var[-3])
print(var[-4])

9
5
8
7
7
8
5
9


In [35]:
import numpy as np
var=np.array([[9,8,7],[4,5,6]])
print(var.ndim)
print(var[0,0])
print(var[0,1])
print(var[0,2])
print(var[1,0])
print(var[1,1])
print(var[1,2])

2
9
8
7
4
5
6


In [39]:
import numpy as np
var=np.array([[[9,8,7],[4,5,6],[5,3,1]]])
print(var.ndim)
print(var[0,0,1])


3
8


In [45]:
#slicing---> [start:step:step]
import numpy as np
var=np.array([9,5,8,7,6])
print(var[0:2])
print(var[::2])

[9 5]
[9 8 6]


In [51]:
import numpy as np
var1=np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var1)
print(var1.ndim)
print("8 to 5", var1[1,1:])
print( var1[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]
2
8 to 5 [8 7 6 5]
[12 13 14 15]


In [53]:
#iterating--->
import numpy as np
var=np.array([9,5,8,7,6])
for i in var:
    print(i)

9
5
8
7
6


In [55]:
var1=np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
for i in var1:
    print(i)


[1 2 3 4 5]
[9 8 7 6 5]
[11 12 13 14 15]


In [57]:
#copy vs view-->
import numpy as np
var=np.array([9,5,8,7,6])
co=var.copy()
print(var)
print(co)

[9 5 8 7 6]
[9 5 8 7 6]


In [65]:
import numpy as np
var=np.array([9,5,8,7,6])
vi=var.view()
print(var)
print(vi)

[9 5 8 7 6]
[9 5 8 7 6]


In [ ]:
'''
Copy---->
- The copy owns the data
- The copy of an arrray is a new array
- The changes made in the copy data does not reflect in the original array

View---->
- The view does not own the data
- A view of the original array
- any changes made to the view will affec the original array
'''

In [67]:
import numpy as np
var=np.array([9,5,8,7,6])
co=var.copy()
var[1]=40
print(var)
print(co)

[ 9 40  8  7  6]
[9 5 8 7 6]


In [69]:
import numpy as np
var=np.array([9,5,8,7,6])
vi=var.view()
var[1]=40
print(var)
print(vi)

[ 9 40  8  7  6]
[ 9 40  8  7  6]


In [75]:
# Joint--->
# join Array: joining means putting content of two or more arrays in a single array
import numpy as np
var1=np.array([9,5,8,7,6])
var2=np.array([1,2,3,4,5])
ar=np.concatenate((var1,var2))
print(ar)

[9 5 8 7 6 1 2 3 4 5]


In [77]:
#split Array- splitting breaks onw array into multiple
import numpy as np
var1=np.array([9,5,8,7,6])
print(var1)
ar=np.array_split(var1,3)
print(ar)

[9 5 8 7 6]
[array([9, 5]), array([8, 7]), array([6])]


In [81]:
#Search Array - search array for an certain value, and return the indexes tha get a match
import numpy as np
var=np.array([9,5,8,7,6,8])
x=np.where(var==8)
print(x)

(array([2, 5], dtype=int64),)


In [87]:
import numpy as np
var=np.array([9,5,8,7,6,8])
x=np.where(var%2==0)
print(x)

(array([2, 4, 5], dtype=int64),)


In [89]:
import numpy as np
var=np.array([9,5,8,7,6,8])
x=np.sort(var)
print(x)

[5 6 7 8 8 9]


In [91]:
#filter Array--->
var=np.array([9,5,2,8])
f=[True,False,False,True]
new=var[f]
print(new)

[9 8]


In [ ]:
#Arithmetic functions: Shuffle, Unique. Resize, Flatten, Ravel

In [97]:
#Shuffle
import numpy as np
var=np.array([1,2,3,4,5,6,7,8,9,10])
np.random.shuffle(var)
print(var)

[ 6 10  8  2  9  7  1  4  3  5]


In [107]:
#unique
import numpy as np
var=np.array([1,2,3,4,5,6,7,8,9,10,1,6,8,7])
x=np.unique(var, return_index=True, return_counts=True)

print(x)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64), array([2, 1, 1, 1, 1, 2, 2, 2, 1, 1], dtype=int64))


In [113]:
#resize
import numpy as np
var=np.array([1,2,3,4,5,6])
x=np.resize(var,(3,2))
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [129]:
#flatten and ravel????
import numpy as np
var=np.array([1,2,3,4,5,6])
x=np.resize(var,(3,2))
print(x)
print(x.flatten(order="C"))
print(np.ravel(x,order="C"))

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
#Insert and delete---->

In [135]:
#Insert
import numpy as np
var=np.array([1,2,3,4,5,6])
print(var)
n=np.insert(var, 2, 40) #(name, position, number to add)
print(n)

[1 2 3 4 5 6]
[ 1  2 40  3  4  5  6]


In [137]:
import numpy as np
var=np.array([[1,2,3],[4,5,6]])
print(var)
n=np.insert(var, 2, [22,23], axis=1) #(name, position, number to add)
print(n)

[[1 2 3]
 [4 5 6]]
[[ 1  2 22  3]
 [ 4  5 23  6]]


In [141]:
import numpy as np
var=np.array([[1,2,3],[4,5,6]])
print(var)
n=np.insert(var, 2, [22,23,24], axis=0) #(name, position, number to add)
print(n)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [22 23 24]]


In [143]:
#append
import numpy as np
var=np.array([1,2,3,4,5,6])
print(var)
n=np.append(var, 6.5) #(name, position, number to add)
print(n)

[1 2 3 4 5 6]
[1.  2.  3.  4.  5.  6.  6.5]


In [145]:
import numpy as np
var=np.array([[1,2,3],[4,5,6]])
print(var)
n=np.append(var, [[45,44,23]], axis=0) #(name, position, number to add)
print(n)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [45 44 23]]


In [157]:
#Delete
import numpy as np
var=np.array([1,2,3,4,5,6])
print(var)
n=np.delete(var,2) 
print(n)

[1 2 3 4 5 6]
[1 2 4 5 6]


In [163]:
#Martix---->
import numpy as np
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print(type(var))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [165]:
import numpy as np
var = np.array([[1,2,3],[4,5,6]])
print(var)
print(type(var))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [173]:
import numpy as np
var1 = np.array([[1,2,3],[4,5,6]])
var2 = np.array([[7,8,9],[10,11,12]])
print("Add: ",var1+var2)
print("Sub: ",var1-var2)
print("Mul: ",var1*var2)


Add:  [[ 8 10 12]
 [14 16 18]]
Sub:  [[-6 -6 -6]
 [-6 -6 -6]]
Mul:  [[ 7 16 27]
 [40 55 72]]


In [ ]:
# Matrix Functions: transpose, Swapaxes, Inverse, Power, Determinate

In [177]:
#Tranpose
import numpy as np
var = np.array([[1,2,3],[4,5,6]])
print(var)
print(np.transpose(var))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [181]:
#Swapaxes
import numpy as np
var = np.array([[1,2,3],[4,5,6]])
print(var)
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [187]:
#inverse
import numpy as np
var = np.array([[1,2],[4,5]])
print(var)
print(np.linalg.inv(var))

[[1 2]
 [4 5]]
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [191]:
#power
import numpy as np
var = np.array([[1,2],[4,5]])
print(var)
print(np.linalg.matrix_power(var,2))
print(np.linalg.matrix_power(var,0))

[[1 2]
 [4 5]]
[[ 9 12]
 [24 33]]
[[1 0]
 [0 1]]


In [193]:
#determinant
import numpy as np
var = np.array([[1,2],[4,5]])
print(var)
print(np.linalg.det(var))

[[1 2]
 [4 5]]
-2.9999999999999996
